POST http://localhost:3333/videos
Content-Type: application/json


{
    "title": "Video Yan",
    "description": "Primeiro video ",
    "duration": 180
    
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/a8065bdd-d981-42da-8ab1-6689afb26771
Content-Type: application/json


{
    "title": "Video YAN AEC",
    "description": "Primeiro video ",
    "duration": 180
}


###

DELETE  http://localhost:3333/videos/ab26c344-8a7b-4ef2-8b4e-9739039ad9c3